CREATE TABLE GameMap(Id INT NOT NULL AUTO_INCREMENT,xCord int NOT NULL, yCord int NOT NULL, cellAlive bit  NOT NULL, PRIMARY KEY (Id));

CREATE TABLE CommitQueue (Id int NOT NULL AUTO_INCREMENT, xCord int NOT NULL, yCord int NOT NULL, PRIMARY KEY (Id));
